### ISSUE TITLE
Errors when running script

### ISSUE THREAD

**Issue by navyfighter12** [AnthonyBloomer/tmdbv3api#112]
I have been using this api for awhile and has been running great every day. Now I am facing this error when running the script

Traceback (most recent call last):
  File "/navy/./l2.py", line 137, in <module>
    search = tvobj.search(title9)
  File "/usr/local/lib/python3.9/dist-packages/tmdbv3api/objs/tv.py", line 60, in search
    self._call(
  File "/usr/local/lib/python3.9/dist-packages/tmdbv3api/tmdb.py", line 185, in _call
    raise TMDbException(json["errors"])
tmdbv3api.exceptions.TMDbException: ['query must be provided']

Did something change on my end or tmbd?

Thanks

**Comment by navyfighter12** [comment]
This only happens when using it for pulling tv posters. I can grab movies just fine

**Comment by Impre-visible** [comment]
try to uninstall and reinstall the api, I don't have this problem, and where do u defin tvobj ?
