### ISSUE TITLE
'AsObj' object has no attribute 'obj_name'

### ISSUE THREAD

**Issue by meisnate12** [AnthonyBloomer/tmdbv3api#74]
When the code below is run it errors out

```python
import tmdbv3api

TMDb = tmdbv3api.TMDb()
TMDb.api_key = <redacted>
TMDb.language = "en"
print(tmdbv3api.Movie().details(658009))
```

```
Traceback (most recent call last):
  File "X:\Documents\Python\Other\collection_test.py", line 6, in <module>
    print(tmdbv3api.Movie().details(658009))
  File "C:\...\tmdbv3api\as_obj.py", line 38, in __str__
    return str(self.__dict__)
  File "C:\...\tmdbv3api\as_obj.py", line 32, in __repr__
    return self.obj_name
AttributeError: 'AsObj' object has no attribute 'obj_name'
```

**Comment by AnthonyBloomer** [comment]
@meisnate12, thank you for raising this issue. I've updated `__repr__` to return the TMDb object rather than returning the media title like before. I actually think this would be more useful to quickly get the media details.

**Comment by AnthonyBloomer** [comment]
[1.7.4](https://pypi.org/project/tmdbv3api/1.7.4/) has been pushed to PyPi.
